### PR TITLE
Change of /var/lib/valkey/data is done in Dockerfile

### PR DESCRIPTION
**Pull request by phracek**
Change of /var/lib/valkey/data is done in /usr/libexec/container-setup.

This change makes problem during the building container 
```
chmod: changing permissions of '/var/lib/valkey/data': Operation not permitted
error building at STEP "RUN getent group valkey &> /dev/null || groupadd -r valkey &> /dev/null &&     usermod -l valkey -aG valkey -c 'Valkey Server' default &> /dev/null &&     INSTALL_PKGS="policycoreutils gettext bind valkey" &&     dnf install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     dnf -y clean all --enablerepo='*' &&     valkey-server --version | grep -qe "^Server v=$VALKEY_VERSION\." && echo "Found VERSION $VALKEY_VERSION" &&     mkdir -p $VALKEY_LIB/data && chown -R valkey:0 $VALKEY_LIB &&     mkdir -p $VALKEY_RUN && chown -R valkey:0 $VALKEY_RUN &&     chmod -R ug+rwX $VALKEY_RUN &&     chmod -R ug+rwX $VALKEY_LIB &&     [[ "$(id valkey)" == "uid=1001(valkey)"* ]]": error while running runtime: exit status 1
time="2024-08-20T11:06:45Z" level=error msg="exit status 1"
Error: Error: buildah exited with code 1
Trying to pull quay.io/sclorg/s2i-core-c10s:c10s...
Getting image source signatures
```

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
@notroj Can you please have a look at this issue. During the building and pushing to quay.io registry it failed with reason mentioned in description of this pull request. Thanks. In case of review please "Approve" it. thanks.

**Review by notroj — APPROVED** [review]
LGTM, thanks @phracek

**Comment by phracek** [comment]
[test]

**Review by jamacku — APPROVED** [review]

**Pull request merged**
